server:
  port: 4410

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: practice
#      auto-index-creation: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
